version: "2.2"

services:
  postgres:
    image: postgres
    container_name: philister_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  cache:
    image: redis:alpine
    container_name: philister_cache
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/
